### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by arturspon** [arturspon/Palavrinhas#1]
- [x] Permitir utilização do teclado no pc
- [x] Permitir apenas palavras existentes
- [x] Escurecer letras já utilizadas
- [x] Colocar borda na linha atual
- [x] Melhorar responsividade
- [x] Ao clicar 'ENTER' tentar confirmar palavra
- [x] Melhorar design
- [x] Permitir compartilhar resultados
- [ ] Mostrar últimos jogos na página inicial
- [ ] Adicionar cronômetro
- [x] Aguardar oponente entrar para iniciar partida
- [x] Mostrar toast quando palavra for inválida
- [x] Utilizar banco de palavras [VERO](https://pt-br.libreoffice.org/projetos/vero)
- [x] Perder se errar a última tentativa
- [x] Definir ID do oponente logo quando ele entrar
- [ ] Sistema de matchmaking
- [x] Refatorar função de criar partida para um arquivo separado
- [x] Permitir jogar outra partida sem voltar para tela inicial
- [x] Criar modo singleplayer
- [ ] Refatorar código em componentes
- [ ] Salvar hora que o jogo iniciou e acabou
- [x] Criar modal com explicação das regras
- [x] Adicionar animações CSS para quando aperta uma letra
- [x] Adicionar animações CSS para quando uma palavra é inválida
- [x] Permitir ver resultados após finalizar partida
- [x] Permitir jogar de novo com mesmo oponente após finalizar (add btn jogar de novo)
- [ ] Focar input na tela ao entrar, as vezes vai digitar e digita na barra de endereços
- [ ] Permitir selecionar posição com o mouse para inserir letra
- [ ] Colocar timeout pra desinscrever do listener do db ou quando perde o foco da janela, pensar em algo
- [ ] Não permitir mesmo jogador abrir mais que uma sala ao mesmo tempo
- [ ] Permitir compartilhar imagem no whatsapp com tela final do resultado
- [ ] Adicionar efeitos sonoros
- [x] Mudar fonte do site todo
- [x] Criar logo
- [x] Adicionar logo como favicon
- [x] Implementar debound de 1s para salvar no banco
- [ ] Permitir reportar palavra errada ou sugerir palavra nova
- [x] Criar regras de segurança no firebase
- [x] Salvar palavras inválidas numa coleção para depois conferir e adicionar as necessárias
- [ ] Adicionar botão para baixar o app na Play Store (mostrar somente para dispositivos Android)
- [ ] Adicionar anúncios
- [x] Implementar transação ao clicar em rematch
- [x] Se o jogador não aceita o rematch o jogo do outro começa mesmo assim
- [ ] Adicionar toast quando usuário clicar para confirmar porém não tiver completado a palavra ainda
- [ ] Traduzir jogo para o inglês
- [ ] Criar botão para pedir dica, essa dica mostra uma letra aleatória da palavra. Os 2 jogadores precisam concordar em aceitar a dica.
- [x] Criar cloud functions para contar total de partidas e outras estatísticas 
- [ ] Permitir convidar jogadores recentes e enviar notificação para ele
- [ ] Pedir nome ao usuário
- [x] Criar documento para usuário
- [ ] Desinscrever listener do db antes de sair da página (beforeDestroy())
